/**
 * Sidebar
 */
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

/**
 * Tutor
 */
export const TUTOR_MODAL_TOGGLE = "TUTOR_MODAL_TOGGLE";
export const TUTOR_SIGN_UP = "TUTOR_SIGN_UP";
export const TUTOR_SIGN_UP_SUCCESS = "TUTOR_SIGN_UP_SUCCESS";
export const TUTOR_SIGN_UP_FAIL = "TUTOR_SIGN_UP_FAIL";

/**
 * Auth
 */
export const GET_AUTH_SIGN_IN = "GET_AUTH_SIGN_IN";
export const GET_AUTH_SIGN_IN_SUCCESS = "GET_AUTH_SIGN_IN_SUCCESS";
export const GET_AUTH_SIGN_IN_FAIL = "GET_AUTH_SIGN_IN_FAIL";

export const GET_AUTH_SIGN_OUT = "GET_AUTH_SIGN_OUT";
export const GET_AUTH_SIGN_OUT_SUCCESS = "GET_AUTH_SIGN_OUT_SUCCESS";
export const GET_AUTH_SIGN_OUT_FAIL = "GET_AUTH_SIGN_OUT_FAIL";

export const GET_AUTH_SIGN_UP = "GET_AUTH_SIGN_UP";
export const GET_AUTH_SIGN_UP_SUCCESS = "GET_AUTH_SIGN_UP_SUCCESS";
export const GET_AUTH_SIGN_UP_FAIL = "GET_AUTH_SIGN_UP_FAIL";

export const GET_AUTH_FORGOT_PASSWORD = "GET_AUTH_FORGOT_PASSWORD";
export const GET_AUTH_FORGOT_PASSWORD_SUCCESS =
  "GET_AUTH_FORGOT_PASSWORD_SUCCESS";
export const GET_AUTH_FORGOT_PASSWORD_FAIL = "GET_AUTH_FORGOT_PASSWORD_FAIL";

export const GET_AUTH_RESET_PASSWORD = "GET_AUTH_RESET_PASSWORD";
export const GET_AUTH_RESET_PASSWORD_SUCCESS =
  "GET_AUTH_RESET_PASSWORD_SUCCESS";
export const GET_AUTH_RESET_PASSWORD_FAIL = "GET_AUTH_RESET_PASSWORD_FAIL";

export const AUTH_UPDATE_PLAN = "AUTH_UPDATE_PLAN";

/**
 * Connections
 */
export const GET_CONNECTIONS = "GET_CONNECTIONS";
export const GET_CONNECTIONS_SUCCESS = "GET_CONNECTIONS_SUCCESS";
export const GET_CONNECTIONS_FAIL = "GET_CONNECTIONS_FAIL";

/**
 * Plans
 */
export const GET_PLANS = "GET_PLANS";
export const GET_PLANS_SUCCESS = "GET_PLANS_SUCCESS";
export const GET_PLANS_FAIL = "GET_PLANS_FAIL";

/**
 * Levels
 */
export const GET_LEVELS = "GET_LEVELS";
export const GET_LEVELS_SUCCESS = "GET_LEVELS_SUCCESS";
export const GET_LEVELS_FAIL = "GET_LEVELS_FAIL";
/**
 * Jobs
 */
export const GET_JOBS = "GET_JOBS";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAIL = "GET_JOBS_FAIL";

/**
 * TUTORS
 */
export const GET_TUTORS = "GET_TUTORS";
export const GET_TUTORS_SUCCESS = "GET_TUTORS_SUCCESS";
export const GET_TUTORS_FAIL = "GET_TUTORS_FAIL";

/**
 * SUBJECTS
 */
export const GET_SUBJECTS = "GET_SUBJECTS";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_FAIL = "GET_SUBJECTS_FAIL";

/**
 * SCHOOLS
 */
export const GET_SCHOOLS = "GET_SCHOOLS";
export const GET_SCHOOLS_SUCCESS = "GET_SCHOOLS_SUCCESS";
export const GET_SCHOOLS_FAIL = "GET_SCHOOLS_FAIL";

export const INIT_APP = "INIT_APP";

export const GET_BLOG_LIST = "GET_BLOG_LIST";
export const GET_BLOG_LIST_SUCCESS = "GET_BLOG_LIST_SUCCESS";
export const GET_BLOG_LIST_FAIL = "GET_BLOG_LIST_FAIL";
